### ISSUE TITLE
Minitest + capybara + fixtures compatibility?

### ISSUE THREAD

**Issue by mikecmpbll** [amatsuda/database_rewinder#27]
I'm trying to use database rewinder with my minitest, capybara, fixtures based test stack but I can't get it to work. It appears to remove all my fixtures and then load them again for every test at the moment.

If anyone's got any experience of using using database rewinder with this stack could you provide an example?

**Comment by mikecmpbll** [comment]
Hold up, the truncating might be Rails, I need to investigate this further. Would be interested still to hear if anyone's had any experience with this combination though.

**Comment by mhluska** [comment]
@mikecmpbll did you figure this out?
