### ISSUE TITLE
retain existing data in tables

### ISSUE THREAD

**Issue by murtyk** [amatsuda/database_rewinder#30]
Hi,

Is there a configuration option to retain records existing before the test run? Say, table accounts has 3 records with ids: 1, 2, 3. During a js: true test, new records with ids 4 and 5 get inserted in accounts table. After the test complete, can the db rewinder delete all records in accounts with id > 3?

**Comment by amatsuda** [comment]
Hrm, interesting, but no, there're no such feature.
Feel free to work on a PR if you think you really need it :)
