### ISSUE TITLE
0.7.0 foreign key error occurred

### ISSUE THREAD

**Issue by mizunago** [amatsuda/database_rewinder#44]
hello, I like this gem.
Just updated to version from `0.6.5` to `0.7.0` and got this error message.
Do you have any information?

<pre>
An error occurred in a `before(:suite)` hook.
Failure/Error: DatabaseRewinder.clean_with(:truncation)

Mysql2::Error:
  Cannot delete or update a parent row: a foreign key constraint fails (`test`.`comments`, CONSTRAINT `fk_rails_78d9619ae2` FOREIGN KEY (`report_id`) REFERENCES `reports` (`report_id`))
# ./spec/spec_helper.rb:50:in `block (2 levels) in <top (required)>'
</pre>

**Comment by mizunago** [comment]
i'm use rails `4.2.7.1`, ruby `2.3.1`

**Comment by amatsuda** [comment]
@mizunago You're using MySQL, right?

**Comment by joker1007** [comment]
I met same error and wrote patch.
I will send PR soon.

**Comment by mizunago** [comment]
@amatsuda Yes, I'm using MySQL `5.7.16`.
@joker1007 thanks!!
