### ISSUE TITLE
Database Support Outside Postgres?

### ISSUE THREAD

**Issue by chrishough** [amatsuda/database_rewinder#51]
On https://github.com/DatabaseCleaner/database_cleaner they list the following types...
<table>
  <tbody>
    <tr>
      <th>ORM</th>
      <th>Truncation</th>
      <th>Transaction</th>
      <th>Deletion</th>
    </tr>
    <tr>
      <td> ActiveRecord </td>
      <td> Yes</td>
      <td> <b>Yes</b></td>
      <td> Yes</td>
    </tr>
    <tr>
      <td> DataMapper</td>
      <td> Yes</td>
      <td> <b>Yes</b></td>
      <td> No</td>
    </tr>
    <tr>
      <td> CouchPotato</td>
      <td> <b>Yes</b></td>
      <td> No</td>
      <td> No</td>
    </tr>
    <tr>
      <td> MongoMapper</td>
      <td> <b>Yes</b></td>
      <td> No</td>
      <td> No</td>
    </tr>
    <tr>
      <td> Mongoid</td>
      <td> <b>Yes</b></td>
      <td> No</td>
      <td> No</td>
    </tr>
    <tr>
      <td> Sequel</td>
      <td> <b>Yes</b></td>
      <td> Yes</td>
      <td> No</td>
    </tr>
    <tr>
      <td>Redis</td>
      <td><b>Yes</b></td>
      <td>No</td>
      <td>No</td>
    </tr>
    <tr>
      <td>Ohm</td>
      <td><b>Yes</b></td>
      <td>No</td>
      <td>No</td>
    </tr>
    <tr>
      <td>Neo4j</td>
      <td>Yes</td>
      <td>Yes*</td>
      <td>Yes*</td>
    </tr>
  </tbody>
</table>

When reviewing this file https://github.com/amatsuda/database_rewinder/blob/master/lib/database_rewinder/active_record_monkey.rb my pair and I discovered it only supports Postgres, SQL Lite 3, and Mysql. 

Do you have plans to support other databases i.e. MongoDB?

**Comment by amatsuda** [comment]
If you mean other SQL based relational databases by "other databases" (e.g. Oracle, SQLServer, Firebird, etc.) the answer is absolutely yes. Please send a patch.
If you meant to say non-RDBMS kind of databases such as document-oriented database, graph database, object database, the answer is no. These are out of this library's scope.

**Comment by chrishough** [comment]
Thank you for your feedback, I was primarily curious about MongoDB.
