### ISSUE TITLE
Can't delete referenced records on Heroku CI

### ISSUE THREAD

**Issue by oakbow** [amatsuda/database_rewinder#62]
Heroku CI is an auto-testing environment like  Circle CI. 
I am using Rspec with database_rewinder for refreshing testing database on PostgreSQL(a heroku add-on named `heroku postgres`).
And when it runs for deleting records which is referenced other records, an error occurs like this;

```
An error occurred in a `before(:suite)` hook.
Failure/Error: DatabaseRewinder.clean_all
ActiveRecord::InvalidForeignKey:
  PG::ForeignKeyViolation: ERROR:  update or delete on table "images" violates foreign key constraint "fk_rails_2c502f515d" on table "user_images"
  DETAIL:  Key (uuid)=(e88bd165-881f-4ac0-890c-729b1759d804) is still referenced from table "user_images".
```

I heard ( but not convinced) that  database_rewinder needs `SUPERUSER` permission on PostgreSQL to delete referenced records, but it is impossible on `heroku postgres`.
Do I have any way to resolve this problem?

**Comment by amatsuda** [comment]
I just came up with an adhoc solution (f268a77efbb24c9a7c26744535a6abd39d29a81f) against this issue after 5.years.since your report, and pushed a new gem versioned 0.9.8 with the patch.

Thanks!
