### ISSUE TITLE
Support for Rails 6.1.0

### ISSUE THREAD

**Issue by crigor** [amatsuda/database_rewinder#75]
Hi Akira. Thank you for creating this gem.

database_rewinder currently doesn't work on rails 6.1.0 because ActiveRecord::Base.configurations returns a hash with symbols as keys. There are 2 PRs that solve this problem and https://github.com/amatsuda/database_rewinder/pull/70 also removes the rails 6.2 deprecation warnings.

@JuanitoFatas Does your PR need more changes?

**Comment by JuanitoFatas** [comment]
Hey Christopher ☺️!! 

#70 has been working fine with my personal Rails app since 6.1 (now 6.2)!

I am happy to follow up with any compatible change if I miss anything.

**Comment by harunorimurata** [comment]
@JuanitoFatas
Hi, Juanito-san!
Can you please fix #70 ?
It failed to build on Rails 6.0.
