### ISSUE TITLE
How to use with capybara-webkit

### ISSUE THREAD

**Issue by dgilperez** [amatsuda/database_rewinder#8]
Hi!

I'm trying the gem and find issues with ``capybara-webkit`` tests, where deletion starts  before the test has finished. With DatabaseCleaner there are different strategies to deal with the issue, such as [this of rspectacular](https://github.com/jfelchner/rspectacular/blob/master/lib/rspectacular/plugins/database_cleaner.rb). 

Is this possible with ``database_rewinder``?

Thanks for the great work!

**Comment by rzane** [comment]
Hi @dgilperez, I also had this problem. Moving all of my capybara requires below my RSpec.configure block fixed it for me. I got the idea from https://github.com/jnicklas/capybara/issues/1089#issuecomment-71767918.

**Comment by deeeki** [comment]
@rzane Thank you for your helpful comment! I'm gonna close this issue.
