### ISSUE TITLE
No tables are cleaned in Rails 7 + MySQL

### ISSUE THREAD

**Issue by osyoyu** [amatsuda/database_rewinder#82]
Setup: Ruby 3.0.3, Rails 7.0.1, mysql2 0.5.3, MySQL 5.7.28

`DatabaseRewinder.clean` has no effect (no DELETE queries are executed) in Rails 7.
After some investigation, I have found out that [tables_inserted](https://github.com/amatsuda/database_rewinder/blob/1d9b2f2d06c4e2137d3dabd9ef424a09f66fcd69/lib/database_rewinder/cleaner.rb#L21) is always empty, which results in no tables being cleaned.

I strongly suspect that this is caused by https://github.com/rails/rails/commit/55199212542d8d8536e5bb93c43f1be50730ae74, affecting database_rewinder's monkey patches in some way (in fact, database_rewinder works perfect before this commit).
This commit removes `alias_method :raw_execute, :execute` in DatabaseStatements, which effectively removes the call to ConnectionAdapters#execute patched by database_rewinder. As a result, no tables are registered as dirty.

**Comment by amatsuda** [comment]
I believe this issue has been fixed via 6113141a8d72451b4ed88bdc02c13a527d5d421b, and I just published 0.9.7 gem that includes the fix.

Thank you for a very well detailed description. That was super helpful!

**Comment by osyoyu** [comment]
Thank you for your quick fix! I have tested out 0.9.7 and see no more issues 👍
